# SPDX-License-Identifier: CC0-1.0
[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.11.0"
ufmt = "0.2.0"
hal = { path = "../hal" }

[build-dependencies]
memorymap-compiler = { git = "https://github.com/QBayLogic/clash-protocols-memmap", rev = "ab96b206566f23889549db5c6159ccb1bcfa2d13", package = "memorymap-compiler" }
